// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyPQOjjLQYJubCa96puSDnfrJMjsHoVFs',
    appId: '1:211317591161:web:4848b67029f83a320718a8',
    messagingSenderId: '211317591161',
    projectId: 'driver-ae64a',
    authDomain: 'driver-ae64a.firebaseapp.com',
    storageBucket: 'driver-ae64a.firebasestorage.app',
    measurementId: 'G-5J7KN6T9Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYYMsuALKxVhT8B1e2jy24pZhWrxRIrGo',
    appId: '1:211317591161:android:2686a11ac56af7880718a8',
    messagingSenderId: '211317591161',
    projectId: 'driver-ae64a',
    storageBucket: 'driver-ae64a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKI4SBCTsSMlO8VZSzpKEwvTXGhYo1UnU',
    appId: '1:211317591161:ios:febff022fc12565e0718a8',
    messagingSenderId: '211317591161',
    projectId: 'driver-ae64a',
    storageBucket: 'driver-ae64a.firebasestorage.app',
    androidClientId: '211317591161-0epskdlpu5hsqobkcr40m1gvq8tjq2ad.apps.googleusercontent.com',
    iosClientId: '211317591161-qthbmc46mtqlpl38vhsa24te12vjv5qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.dirver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKI4SBCTsSMlO8VZSzpKEwvTXGhYo1UnU',
    appId: '1:211317591161:ios:febff022fc12565e0718a8',
    messagingSenderId: '211317591161',
    projectId: 'driver-ae64a',
    storageBucket: 'driver-ae64a.firebasestorage.app',
    androidClientId: '211317591161-0epskdlpu5hsqobkcr40m1gvq8tjq2ad.apps.googleusercontent.com',
    iosClientId: '211317591161-qthbmc46mtqlpl38vhsa24te12vjv5qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.dirver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyPQOjjLQYJubCa96puSDnfrJMjsHoVFs',
    appId: '1:211317591161:web:4b3d4d73088db5ce0718a8',
    messagingSenderId: '211317591161',
    projectId: 'driver-ae64a',
    authDomain: 'driver-ae64a.firebaseapp.com',
    storageBucket: 'driver-ae64a.firebasestorage.app',
    measurementId: 'G-33Q7VZZS3R',
  );
}